-- ==========================================
-- PNLE NURSING BOARD EXAM SEED QUESTIONS
-- 120 Questions across key nursing domains
-- ==========================================
-- IMPORTANT: Replace the user_id below with YOUR actual user ID
-- You can find it in Supabase > Authentication > Users
-- ==========================================

DO $$
DECLARE
  v_user_id UUID := '3c4ca78b-2934-48d5-87ec-a7f01103cd85'; -- <-- PASTE YOUR USER ID HERE
BEGIN

-- ==========================================
-- FUNDAMENTALS OF NURSING (Items 1-20)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'Which of the following is the most appropriate nursing action before administering medication?', 'Check the patient''s insurance', 'Verify the five rights of medication administration', 'Ask the patient if they want the medication', 'Wait for the physician to administer it', 1, 'The five rights (right patient, right drug, right dose, right route, right time) are the standard safety checks before any medication administration.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'The nurse is assessing a patient''s vital signs. Which pulse site is most commonly used for routine assessment?', 'Carotid', 'Radial', 'Apical', 'Femoral', 1, 'The radial pulse is the most accessible and commonly used site for routine vital sign assessment in adults.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which position is most appropriate for a patient undergoing a lumbar puncture?', 'Supine', 'Lateral recumbent with knees drawn up', 'Prone', 'Trendelenburg', 1, 'The lateral recumbent (fetal) position opens the intervertebral spaces maximally, facilitating needle insertion.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'A nurse notes that a patient''s urine output has been 20 mL/hr for the past 3 hours. This finding most likely indicates:', 'Normal kidney function', 'Decreased renal perfusion', 'Fluid overload', 'Urinary tract infection', 1, 'Normal urine output is 30-50 mL/hr. Output less than 30 mL/hr suggests decreased renal perfusion and potential kidney compromise.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which nursing theory is associated with the concept of "Self-Care Deficit"?', 'Florence Nightingale', 'Dorothea Orem', 'Virginia Henderson', 'Hildegard Peplau', 1, 'Dorothea Orem developed the Self-Care Deficit Theory, which focuses on the patient''s ability to perform self-care activities.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'When performing hand hygiene with an alcohol-based hand rub, what is the minimum duration?', '5 seconds', '10 seconds', '20 seconds', '60 seconds', 2, 'The CDC recommends rubbing hands together with alcohol-based sanitizer for at least 20 seconds for effective decontamination.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'The nurse is preparing to insert a nasogastric tube. Which action should be performed FIRST?', 'Lubricate the tip of the tube', 'Measure the tube from nose to earlobe to xiphoid process', 'Position the patient in high Fowler''s position', 'Verify the physician''s order', 3, 'Verifying the physician''s order is always the first step before any invasive procedure.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which of the following is a priority nursing diagnosis for a patient with dyspnea?', 'Impaired physical mobility', 'Ineffective airway clearance', 'Risk for infection', 'Disturbed body image', 1, 'According to Maslow''s hierarchy of needs, airway and breathing take priority, making ineffective airway clearance the most urgent diagnosis.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'The nurse is documenting in a patient''s chart. Which entry is an example of objective data?', 'Patient reports feeling dizzy', 'Patient states "I feel nauseous"', 'Blood pressure is 140/90 mmHg', 'Patient appears anxious', 2, 'Objective data is measurable and observable. A blood pressure reading of 140/90 mmHg is a quantifiable measurement.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'A patient is ordered NPO after midnight for surgery. The nurse should:', 'Remove the water pitcher from the bedside', 'Allow the patient to drink small sips of water', 'Give the patient ice chips if thirsty', 'Tell the patient they can eat breakfast', 0, 'NPO means nothing by mouth. Removing the water pitcher helps prevent accidental intake and maintains the NPO status.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which of the following is the correct sequence for physical examination?', 'Palpation, percussion, inspection, auscultation', 'Inspection, palpation, percussion, auscultation', 'Auscultation, inspection, palpation, percussion', 'Percussion, auscultation, inspection, palpation', 1, 'The correct order is Inspection, Palpation, Percussion, Auscultation (IPPA), except for the abdomen where auscultation precedes palpation and percussion.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'The nurse is caring for an immobile patient. How often should the patient be repositioned to prevent pressure ulcers?', 'Every 30 minutes', 'Every 2 hours', 'Every 4 hours', 'Every 8 hours', 1, 'The standard of care is to reposition immobile patients every 2 hours to relieve pressure and prevent skin breakdown.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which of the following is the most reliable indicator of fluid balance in a patient?', 'Skin turgor', 'Daily weight', 'Blood pressure', 'Urine color', 1, 'Daily weight is the most accurate and reliable indicator of fluid balance. A gain or loss of 1 kg equals approximately 1 liter of fluid.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'A patient is receiving oxygen via nasal cannula at 2 L/min. What is the approximate FiO2?', '24%', '28%', '32%', '36%', 1, 'Each liter of oxygen via nasal cannula increases FiO2 by approximately 4%. Room air is 21%, so 2 L/min provides approximately 28%.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'The nurse finds a patient unresponsive. What should the nurse do FIRST?', 'Begin chest compressions', 'Call for help', 'Check for a pulse', 'Open the airway', 1, 'According to the American Heart Association BLS guidelines, after finding an unresponsive patient, the nurse should call for help (activate emergency response) first.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which type of isolation precaution is required for a patient with tuberculosis?', 'Contact precautions', 'Droplet precautions', 'Airborne precautions', 'Standard precautions only', 2, 'Tuberculosis is transmitted via airborne droplet nuclei, requiring airborne precautions with an N95 respirator and negative pressure room.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'When administering an intramuscular injection to an adult, which site allows the largest volume?', 'Deltoid', 'Vastus lateralis', 'Ventrogluteal', 'Dorsogluteal', 2, 'The ventrogluteal site is the preferred site for IM injections in adults because it accommodates larger volumes (up to 3 mL) and has fewer complications.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'A nurse is obtaining informed consent. Which statement is TRUE?', 'The nurse obtains the consent', 'The physician explains the procedure and the nurse witnesses the signature', 'Informed consent is not needed for minor procedures', 'A family member can sign without the patient''s knowledge', 1, 'The physician is responsible for explaining the procedure, risks, benefits, and alternatives. The nurse witnesses the patient''s signature and ensures understanding.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'Which stage of pressure ulcer involves full-thickness tissue loss with exposed bone, tendon, or muscle?', 'Stage II', 'Stage III', 'Stage IV', 'Unstageable', 2, 'Stage IV pressure ulcers involve full-thickness tissue loss with exposed bone, tendon, or muscle. They may include undermining and tunneling.', 'Fundamentals of Nursing', 'nursing'),
(v_user_id, 'The nurse is performing a sterile dressing change. Which action would contaminate the sterile field?', 'Keeping the sterile field within sight', 'Holding sterile items above waist level', 'Reaching across the sterile field', 'Using sterile forceps to arrange supplies', 2, 'Reaching across a sterile field contaminates it because the arm passes over the sterile area, potentially dropping microorganisms onto the field.', 'Fundamentals of Nursing', 'nursing');

-- ==========================================
-- MEDICAL-SURGICAL NURSING (Items 21-50)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'A patient with diabetes mellitus has a blood glucose level of 45 mg/dL. Which intervention should the nurse perform FIRST?', 'Administer regular insulin', 'Give 15 grams of fast-acting carbohydrate', 'Call the physician', 'Recheck the blood glucose in 30 minutes', 1, 'A blood glucose of 45 mg/dL indicates hypoglycemia. The immediate intervention is to give 15g of fast-acting carbohydrate (juice, glucose tablets) following the 15-15 rule.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A nurse is caring for a client with hyperkalemia. Which of the following ECG changes would the nurse most likely expect?', 'Inverted T waves', 'Presence of U waves', 'Tall, peaked T waves', 'Shortened QT interval', 2, 'Hyperkalemia typically manifests on an ECG as tall, peaked T waves, widened QRS complex, and a prolonged PR interval.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which diet is most appropriate for a patient with chronic kidney disease?', 'High protein, low sodium', 'Low protein, low potassium, low sodium', 'High potassium, high fiber', 'Regular diet with fluid restriction only', 1, 'CKD patients require a diet low in protein (to reduce urea), low in potassium (to prevent hyperkalemia), and low in sodium (to control fluid retention).', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with heart failure is prescribed furosemide (Lasix). Which lab value should the nurse monitor closely?', 'Calcium', 'Potassium', 'Magnesium', 'Sodium', 1, 'Furosemide is a loop diuretic that causes significant potassium loss. Hypokalemia can lead to dangerous cardiac arrhythmias.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'The nurse is caring for a patient 2 hours post-thyroidectomy. Which assessment finding requires IMMEDIATE intervention?', 'Hoarseness of voice', 'Tingling around the mouth', 'Sore throat', 'Temperature of 37.5°C', 1, 'Tingling around the mouth (circumoral paresthesia) after thyroidectomy suggests hypocalcemia due to accidental removal or damage to the parathyroid glands, which is a medical emergency.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with a chest tube has continuous bubbling in the water seal chamber. This indicates:', 'Normal functioning', 'An air leak in the system', 'The lung has fully re-expanded', 'The chest tube is clamped', 1, 'Continuous bubbling in the water seal chamber indicates an air leak in the drainage system. Intermittent bubbling is expected during expiration or coughing.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which assessment finding is MOST indicative of right-sided heart failure?', 'Pulmonary edema', 'Peripheral edema', 'Pink frothy sputum', 'Crackles in lungs', 1, 'Right-sided heart failure causes systemic congestion, leading to peripheral edema, jugular vein distension, and hepatomegaly. Left-sided failure causes pulmonary symptoms.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with cirrhosis is at greatest risk for which complication?', 'Pulmonary embolism', 'Esophageal varices', 'Renal calculi', 'Peptic ulcer disease', 1, 'Cirrhosis causes portal hypertension, which leads to the development of esophageal varices. Rupture of these varices can cause life-threatening hemorrhage.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Trousseau''s sign is assessed by:', 'Tapping the facial nerve', 'Inflating a blood pressure cuff on the arm', 'Checking deep tendon reflexes', 'Palpating the thyroid gland', 1, 'Trousseau''s sign is elicited by inflating a BP cuff above systolic pressure for 3 minutes; a positive result (carpal spasm) indicates hypocalcemia.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with COPD should receive oxygen at which flow rate?', '1-2 L/min', '4-6 L/min', '8-10 L/min', '10-12 L/min', 0, 'COPD patients rely on hypoxic drive for respiration. High-flow oxygen can suppress this drive, so 1-2 L/min is recommended to maintain SpO2 at 88-92%.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient is admitted with acute pancreatitis. Which lab value would the nurse expect to be ELEVATED?', 'Blood glucose', 'Serum amylase', 'Serum albumin', 'Hemoglobin', 1, 'Serum amylase and lipase are markedly elevated in acute pancreatitis as pancreatic enzymes leak into the bloodstream.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'The nurse is caring for a burn patient. Which type of burn involves the epidermis and part of the dermis, with blistering?', 'Superficial burn', 'Superficial partial-thickness burn', 'Deep partial-thickness burn', 'Full-thickness burn', 1, 'Superficial partial-thickness (second-degree) burns involve the epidermis and upper dermis, characterized by blisters, pain, and a moist appearance.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with a hemoglobin of 7 g/dL is MOST likely to exhibit which symptom?', 'Hypertension', 'Fatigue and tachycardia', 'Bradycardia', 'Flushed skin', 1, 'Severe anemia (Hgb < 8 g/dL) results in decreased oxygen-carrying capacity, leading to fatigue, tachycardia, pallor, and dyspnea as compensatory mechanisms activate.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which complication should the nurse monitor for in a patient receiving a blood transfusion within the first 15 minutes?', 'Iron overload', 'Acute hemolytic reaction', 'Fluid overload', 'Delayed allergic reaction', 1, 'Acute hemolytic transfusion reactions, caused by ABO incompatibility, typically occur within the first 15 minutes. Signs include fever, chills, flank pain, and hypotension.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with Addison''s disease would exhibit which of the following?', 'Hyperglycemia', 'Hypertension', 'Bronze skin pigmentation', 'Weight gain', 2, 'Addison''s disease (adrenal insufficiency) causes hyperpigmentation due to excess ACTH stimulating melanocytes, along with hypotension, hyponatremia, and hyperkalemia.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'The nurse is teaching a patient about warfarin (Coumadin). Which statement indicates the patient needs MORE teaching?', '"I should avoid green leafy vegetables completely."', '"I will have regular INR blood tests."', '"I should report any unusual bleeding."', '"I will use a soft toothbrush."', 0, 'Patients on warfarin should maintain CONSISTENT vitamin K intake, not avoid green leafy vegetables entirely. Sudden changes in vitamin K intake affect INR levels.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which electrolyte imbalance is MOST commonly associated with prolonged vomiting?', 'Hyperkalemia', 'Metabolic alkalosis', 'Respiratory acidosis', 'Hypernatremia', 1, 'Prolonged vomiting causes loss of hydrochloric acid (HCl) from the stomach, leading to metabolic alkalosis with hypokalemia and hypochloremia.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient''s ABG results show: pH 7.30, PaCO2 50 mmHg, HCO3 24 mEq/L. This indicates:', 'Metabolic acidosis', 'Respiratory acidosis', 'Metabolic alkalosis', 'Respiratory alkalosis', 1, 'pH < 7.35 indicates acidosis. Elevated PaCO2 (>45) with normal HCO3 indicates that the respiratory system is the primary cause: respiratory acidosis.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with deep vein thrombosis should be placed on:', 'Bed rest with affected leg in a dependent position', 'Bed rest with affected leg elevated', 'Ambulation as tolerated', 'Active range-of-motion exercises to the affected leg', 1, 'DVT management includes bed rest with the affected extremity elevated above heart level to promote venous return and reduce edema. Avoid massaging the leg.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which assessment finding is characteristic of a tension pneumothorax?', 'Bilateral equal breath sounds', 'Tracheal deviation toward the affected side', 'Tracheal deviation AWAY from the affected side', 'Decreased jugular venous pressure', 2, 'Tension pneumothorax causes increased pressure that pushes the trachea and mediastinum AWAY from the affected side. This is a life-threatening emergency.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with myasthenia gravis is experiencing a myasthenic crisis. The nurse should anticipate:', 'Administration of atropine', 'Administration of edrophonium (Tensilon)', 'Mechanical ventilation', 'Discontinuation of all medications', 2, 'Myasthenic crisis causes severe muscle weakness including respiratory muscles. Mechanical ventilation may be needed while adjusting anticholinesterase medications.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'The nurse is caring for a patient with syndrome of inappropriate antidiuretic hormone (SIADH). The priority intervention is:', 'Fluid restriction', 'Encouraging oral fluid intake', 'Administering hypertonic saline rapidly', 'High-sodium diet only', 0, 'SIADH causes water retention and dilutional hyponatremia. The priority is fluid restriction (typically 500-1000 mL/day) to allow sodium levels to normalize.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A post-operative patient develops atelectasis. Which nursing intervention is MOST appropriate?', 'Administer antibiotics', 'Encourage deep breathing and incentive spirometry', 'Place the patient in a supine position', 'Restrict fluids', 1, 'Incentive spirometry and deep breathing exercises help expand collapsed alveoli and prevent further atelectasis in post-operative patients.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which finding would the nurse expect in a patient with Cushing''s syndrome?', 'Hypotension', 'Moon face and buffalo hump', 'Bronze skin', 'Weight loss', 1, 'Cushing''s syndrome results from excess cortisol, causing moon face, buffalo hump, truncal obesity, hypertension, hyperglycemia, and striae.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient with hepatic encephalopathy should receive which medication?', 'Furosemide', 'Lactulose', 'Metoclopramide', 'Omeprazole', 1, 'Lactulose reduces ammonia levels in the blood by promoting ammonia excretion through the stool, which is the primary treatment for hepatic encephalopathy.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'The nurse is monitoring a patient on heparin therapy. Which lab test is used to monitor its effectiveness?', 'PT/INR', 'aPTT', 'Platelet count', 'Bleeding time', 1, 'Activated partial thromboplastin time (aPTT) is used to monitor heparin therapy. The therapeutic range is 1.5-2.5 times the normal value.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A patient is diagnosed with acute appendicitis. Which nursing action is CONTRAINDICATED?', 'Applying an ice pack to the abdomen', 'Administering prescribed analgesics', 'Applying a heating pad to the abdomen', 'Positioning the patient in a right side-lying position', 2, 'Heat application to the abdomen in appendicitis is contraindicated because it can increase blood flow to the area and promote rupture of the inflamed appendix.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which drug is the antidote for heparin overdose?', 'Vitamin K', 'Protamine sulfate', 'Naloxone', 'Flumazenil', 1, 'Protamine sulfate is the specific antidote for heparin. Vitamin K is the antidote for warfarin, naloxone for opioids, and flumazenil for benzodiazepines.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'A Glasgow Coma Scale score of 8 indicates:', 'Normal neurological function', 'Mild brain injury', 'Moderate brain injury', 'Severe brain injury requiring intubation', 3, 'A GCS score of 8 or less indicates severe brain injury. The GCS ranges from 3 (deep coma) to 15 (fully alert). Intubation is typically indicated for GCS ≤ 8.', 'Medical-Surgical Nursing', 'nursing'),
(v_user_id, 'Which sign is an early indicator of increased intracranial pressure?', 'Bradycardia', 'Change in level of consciousness', 'Fixed and dilated pupils', 'Cushing''s triad', 1, 'A change in level of consciousness (confusion, restlessness, lethargy) is the earliest and most sensitive indicator of increased ICP. Cushing''s triad is a late finding.', 'Medical-Surgical Nursing', 'nursing');

-- ==========================================
-- PHARMACOLOGY (Items 51-70)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'Which classification of drugs is used as first-line treatment for hypertension?', 'Opioid analgesics', 'ACE inhibitors', 'Corticosteroids', 'Antihistamines', 1, 'ACE inhibitors (e.g., enalapril, lisinopril) are first-line agents for hypertension. They work by blocking the conversion of angiotensin I to angiotensin II.', 'Pharmacology', 'nursing'),
(v_user_id, 'A patient is taking digoxin. The nurse should hold the medication and notify the physician if the apical pulse is:', 'Above 100 bpm', 'Below 60 bpm', 'Between 70-80 bpm', 'Irregular', 1, 'Digoxin slows the heart rate. If the apical pulse is below 60 bpm, the nurse should hold the dose and notify the physician to prevent toxicity.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which adverse effect of aminoglycoside antibiotics (e.g., gentamicin) is the nurse MOST concerned about?', 'Constipation', 'Nephrotoxicity and ototoxicity', 'Insomnia', 'Weight gain', 1, 'Aminoglycosides are known for causing nephrotoxicity (kidney damage) and ototoxicity (hearing loss). Monitoring trough/peak levels and creatinine is essential.', 'Pharmacology', 'nursing'),
(v_user_id, 'Nitroglycerin is administered sublingually for angina. The nurse should teach the patient to:', 'Swallow the tablet with water', 'Place under the tongue and allow it to dissolve', 'Chew the tablet thoroughly', 'Take with food', 1, 'Sublingual nitroglycerin must be placed under the tongue and allowed to dissolve for rapid absorption. The patient should feel a slight tingling sensation.', 'Pharmacology', 'nursing'),
(v_user_id, 'A patient receiving morphine sulfate shows pinpoint pupils, respiratory rate of 8, and drowsiness. The nurse should administer:', 'Atropine', 'Epinephrine', 'Naloxone (Narcan)', 'Flumazenil', 2, 'The signs describe opioid overdose. Naloxone (Narcan) is the specific opioid antagonist that reverses respiratory depression, sedation, and miosis.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which instruction should the nurse give a patient starting an MAOI antidepressant?', 'Take the medication with milk', 'Avoid tyramine-rich foods such as aged cheese and wine', 'Take the medication only at bedtime', 'Increase salt intake', 1, 'MAOIs inhibit the breakdown of tyramine. Consuming tyramine-rich foods (aged cheese, wine, smoked meats) can cause a hypertensive crisis.', 'Pharmacology', 'nursing'),
(v_user_id, 'The nurse is administering insulin lispro (Humalog). When should it be given?', '30 minutes before meals', 'At bedtime', '15 minutes before or immediately after meals', '2 hours after meals', 2, 'Insulin lispro is a rapid-acting insulin with onset of 15 minutes. It should be administered 15 minutes before or immediately after starting a meal.', 'Pharmacology', 'nursing'),
(v_user_id, 'A patient on corticosteroid therapy should be monitored for which complication?', 'Hypoglycemia', 'Hyperglycemia', 'Hypotension', 'Weight loss', 1, 'Corticosteroids increase gluconeogenesis and cause insulin resistance, leading to hyperglycemia. Patients may develop steroid-induced diabetes.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which medication requires the nurse to monitor for signs of bleeding, including tarry stools?', 'Acetaminophen', 'Warfarin', 'Metformin', 'Levothyroxine', 1, 'Warfarin is an anticoagulant that increases bleeding risk. Tarry stools (melena) indicate GI bleeding and require immediate medical attention.', 'Pharmacology', 'nursing'),
(v_user_id, 'Metformin (Glucophage) should be held before which type of procedure?', 'Endoscopy', 'Contrast dye studies', 'Bone marrow biopsy', 'Chest X-ray', 1, 'Metformin should be held 48 hours before and after contrast dye procedures due to the risk of lactic acidosis from contrast-induced nephropathy.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which class of antihypertensive drugs commonly causes a dry, persistent cough as a side effect?', 'Beta-blockers', 'Calcium channel blockers', 'ACE inhibitors', 'Angiotensin II receptor blockers', 2, 'ACE inhibitors (e.g., enalapril, captopril) cause bradykinin accumulation, which irritates the lungs and produces a dry, persistent cough in up to 20% of patients.', 'Pharmacology', 'nursing'),
(v_user_id, 'A nurse is administering vancomycin IV. Which complication should be monitored during the infusion?', 'Hyperglycemia', 'Red Man Syndrome', 'Hypertension', 'Constipation', 1, 'Red Man Syndrome (flushing, erythema of the upper body, pruritus) occurs with rapid vancomycin infusion. It should be infused over at least 60 minutes.', 'Pharmacology', 'nursing'),
(v_user_id, 'A patient on lithium therapy has a serum level of 2.0 mEq/L. The nurse should:', 'Continue the medication as prescribed', 'Hold the medication and notify the physician', 'Administer an extra dose', 'Encourage the patient to increase fluid intake', 1, 'The therapeutic range for lithium is 0.6-1.2 mEq/L. A level of 2.0 mEq/L is toxic and the medication should be held immediately while notifying the physician.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which vitamin is essential for the synthesis of clotting factors and is the antidote for warfarin?', 'Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K', 3, 'Vitamin K is essential for synthesizing clotting factors II, VII, IX, and X in the liver. It is the specific antidote for warfarin overdose.', 'Pharmacology', 'nursing'),
(v_user_id, 'Epinephrine is the drug of choice for which emergency condition?', 'Hypertensive crisis', 'Anaphylaxis', 'Diabetic ketoacidosis', 'Pulmonary embolism', 1, 'Epinephrine is the first-line treatment for anaphylaxis. It causes bronchodilation, vasoconstriction, and increased cardiac output to reverse the allergic response.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which side effect is associated with phenytoin (Dilantin)?', 'Hair loss', 'Gingival hyperplasia', 'Hypoglycemia', 'Weight loss', 1, 'Phenytoin commonly causes gingival hyperplasia (overgrowth of gum tissue). Good oral hygiene and regular dental visits are essential for patients on this drug.', 'Pharmacology', 'nursing'),
(v_user_id, 'A patient on isoniazid (INH) for tuberculosis should receive supplemental:', 'Vitamin C', 'Vitamin B6 (pyridoxine)', 'Vitamin B12', 'Iron', 1, 'Isoniazid can cause peripheral neuropathy by depleting vitamin B6 (pyridoxine). Supplementation with pyridoxine prevents this adverse effect.', 'Pharmacology', 'nursing'),
(v_user_id, 'Which medication should NOT be abruptly discontinued?', 'Acetaminophen', 'Beta-blockers', 'Antacids', 'Antibiotics', 1, 'Abrupt discontinuation of beta-blockers can cause rebound hypertension, tachycardia, and angina. They should be tapered gradually over 1-2 weeks.', 'Pharmacology', 'nursing'),
(v_user_id, 'Albuterol (salbutamol) works by:', 'Blocking histamine receptors', 'Stimulating beta-2 adrenergic receptors', 'Inhibiting prostaglandin synthesis', 'Blocking calcium channels', 1, 'Albuterol is a selective beta-2 agonist that causes bronchial smooth muscle relaxation, providing rapid relief of bronchospasm in asthma and COPD.', 'Pharmacology', 'nursing'),
(v_user_id, 'The nurse should instruct a patient taking iron supplements to:', 'Take with an antacid', 'Take with milk for better absorption', 'Take with vitamin C or orange juice', 'Avoid all fluids for 2 hours after', 2, 'Vitamin C (ascorbic acid) enhances iron absorption. Dairy products, antacids, and tea/coffee should be avoided as they inhibit iron absorption.', 'Pharmacology', 'nursing');

-- ==========================================
-- MATERNAL & CHILD HEALTH NURSING (Items 71-95)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'During pregnancy, Nagele''s rule is used to estimate:', 'Gestational age', 'Expected date of delivery', 'Fetal weight', 'Fetal heart rate', 1, 'Nagele''s rule estimates the EDD by subtracting 3 months from the first day of the last menstrual period and adding 7 days (and 1 year if needed).', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Which is the MOST reliable sign of pregnancy?', 'Amenorrhea', 'Fetal heart sounds heard on Doppler', 'Positive pregnancy test', 'Morning sickness', 1, 'Fetal heart sounds detected by Doppler (usually at 10-12 weeks) are a positive (reliable) sign of pregnancy. Amenorrhea and a positive test are presumptive/probable signs.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'A pregnant patient at 38 weeks gestation has a blood pressure of 160/110 mmHg with proteinuria. This MOST likely indicates:', 'Gestational hypertension', 'Preeclampsia with severe features', 'Chronic hypertension', 'HELLP syndrome', 1, 'BP ≥160/110 with proteinuria in the third trimester indicates preeclampsia with severe features. This requires close monitoring and often delivery.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'The drug of choice for preventing seizures in preeclampsia is:', 'Diazepam', 'Magnesium sulfate', 'Phenytoin', 'Hydralazine', 1, 'Magnesium sulfate is the gold standard for seizure prophylaxis and treatment in eclampsia/preeclampsia. It acts as a CNS depressant.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'The antidote for magnesium sulfate toxicity is:', 'Naloxone', 'Calcium gluconate', 'Protamine sulfate', 'Vitamin K', 1, 'Calcium gluconate is the antidote for magnesium sulfate toxicity. Signs of toxicity include loss of deep tendon reflexes, respiratory depression, and cardiac arrest.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'The APGAR score assesses which parameters in a newborn?', 'Height, weight, head circumference, reflexes, color', 'Appearance, Pulse, Grimace, Activity, Respiration', 'Alertness, Pain response, Growth, Appetite, Reflexes', 'Activity, Position, Grasp, Arousal, Responsiveness', 1, 'APGAR stands for Appearance (color), Pulse (heart rate), Grimace (reflex irritability), Activity (muscle tone), and Respiration (breathing effort). Each is scored 0-2.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'A newborn has an APGAR score of 4 at 1 minute. The nurse should:', 'Do nothing as this is normal', 'Begin resuscitative measures', 'Stimulate by rubbing the back only', 'Place the baby skin-to-skin with the mother', 1, 'An APGAR score of 4-6 indicates moderate distress requiring active intervention. A score below 7 requires some form of resuscitation.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Rh-negative mothers should receive RhoGAM at which gestational age?', '12 weeks', '20 weeks', '28 weeks', '36 weeks', 2, 'RhoGAM (anti-D immunoglobulin) is given at 28 weeks gestation and within 72 hours after delivery to prevent Rh sensitization in Rh-negative mothers.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Late decelerations on a fetal heart rate monitor indicate:', 'Head compression', 'Umbilical cord compression', 'Uteroplacental insufficiency', 'A normal pattern', 2, 'Late decelerations begin after the peak of a contraction and indicate uteroplacental insufficiency. This is an ominous sign requiring immediate intervention.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'A primigravida in active labor is dilated at 6 cm. Which stage of labor is this?', 'Latent phase of Stage 1', 'Active phase of Stage 1', 'Transition phase of Stage 1', 'Stage 2', 1, 'The active phase of Stage 1 labor is from 4-7 cm dilation, characterized by regular contractions and more rapid cervical change.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Immediately after delivery, the nurse should assess the newborn''s airway by:', 'Inserting an endotracheal tube', 'Suctioning the mouth first, then the nose', 'Placing the baby prone', 'Waiting for the baby to cry', 1, 'The mouth is suctioned before the nose to prevent aspiration of oropharyngeal secretions that could be inhaled if the nose were stimulated first.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Which breastfeeding position is recommended for a mother who had a cesarean delivery?', 'Cradle hold', 'Cross-cradle hold', 'Football (clutch) hold', 'Side-lying position', 2, 'The football (clutch) hold keeps the baby away from the abdominal incision, reducing pain and pressure on the surgical site.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'A newborn has a positive Babinski reflex. The nurse should:', 'Document this as a normal finding', 'Report this immediately to the physician', 'Perform further neurological assessment', 'Restrict the infant''s movement', 0, 'A positive Babinski reflex (fanning of toes when sole is stroked) is NORMAL in infants up to 2 years old. It indicates an immature nervous system.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'The normal fetal heart rate range is:', '80-100 bpm', '110-160 bpm', '160-200 bpm', '60-80 bpm', 1, 'The normal fetal heart rate is 110-160 beats per minute. Rates outside this range may indicate fetal distress and require further assessment.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Which sign indicates placenta previa rather than placental abruption?', 'Painful vaginal bleeding', 'Painless bright red vaginal bleeding', 'Rigid board-like abdomen', 'Dark red vaginal bleeding', 1, 'Placenta previa presents with painless, bright red bleeding. Abruptio placentae presents with painful, dark red bleeding and a rigid, tender abdomen.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'At what age should an infant double their birth weight?', '2 months', '4-6 months', '9 months', '12 months', 1, 'Infants typically double their birth weight by 4-6 months of age and triple it by 12 months.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'The nurse suspects a child has epiglottitis. Which action is CONTRAINDICATED?', 'Keeping the child calm', 'Maintaining the child in an upright position', 'Examining the throat with a tongue depressor', 'Preparing for possible intubation', 2, 'Examining the throat with a tongue depressor is contraindicated in suspected epiglottitis as it can cause laryngospasm and complete airway obstruction.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Phototherapy is used to treat neonatal jaundice by:', 'Increasing bile production', 'Converting indirect bilirubin to a water-soluble form', 'Stimulating the liver to metabolize bilirubin', 'Reducing red blood cell breakdown', 1, 'Phototherapy uses light to convert unconjugated (indirect) bilirubin in the skin into a water-soluble isomer that can be excreted without liver conjugation.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Which immunization is given at birth?', 'BCG and Hepatitis B', 'OPV and DPT', 'MMR', 'Varicella', 0, 'BCG (Bacillus Calmette-Guérin) for tuberculosis and Hepatitis B vaccine are given at birth as part of the Philippine immunization schedule.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'A child with Kawasaki disease should be monitored for which cardiac complication?', 'Mitral valve stenosis', 'Coronary artery aneurysm', 'Atrial septal defect', 'Coarctation of the aorta', 1, 'Kawasaki disease can cause coronary artery aneurysms if untreated. Intravenous immunoglobulin (IVIG) and aspirin are the standard treatments.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Meconium is normally passed by the newborn within:', '6 hours', '12-24 hours', '48-72 hours', '5 days', 1, 'Most newborns pass meconium (dark green-black first stool) within the first 12-24 hours of life. Failure to pass meconium may indicate intestinal obstruction.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Which developmental milestone is expected at 6 months of age?', 'Walking independently', 'Sitting with support', 'Speaking in sentences', 'Toilet training', 1, 'At 6 months, infants can typically sit with support, roll over, grasp objects, babble, and recognize familiar faces.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'Pyloric stenosis in infants classically presents with:', 'Bile-stained vomiting', 'Non-bilious projectile vomiting', 'Bloody diarrhea', 'Chronic constipation', 1, 'Pyloric stenosis causes hypertrophy of the pyloric muscle, resulting in non-bilious, projectile vomiting typically starting at 2-5 weeks of age. An olive-shaped mass may be palpable.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'The nurse is teaching a mother about introducing solid foods. At what age should complementary feeding begin?', '2 months', '4 months', '6 months', '8 months', 2, 'WHO and Philippine DOH recommend exclusive breastfeeding for the first 6 months, with complementary feeding starting at 6 months along with continued breastfeeding.', 'Maternal & Child Health', 'nursing'),
(v_user_id, 'A post-partum mother is soaking more than one pad per hour. This indicates:', 'Normal lochia', 'Post-partum hemorrhage', 'Urinary incontinence', 'Menstrual resumption', 1, 'Soaking more than one pad per hour indicates postpartum hemorrhage, which requires immediate intervention including uterine massage and possible medication.', 'Maternal & Child Health', 'nursing');

-- ==========================================
-- COMMUNITY HEALTH & PSYCHIATRIC NURSING (Items 96-120)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'The primary goal of community health nursing is:', 'Treatment of disease', 'Promotion of health and prevention of disease', 'Hospital-based care', 'Individual patient care', 1, 'Community health nursing focuses on health promotion, disease prevention, and maintaining the health of the population through community-based interventions.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'Which level of disease prevention includes immunization?', 'Primordial', 'Primary', 'Secondary', 'Tertiary', 1, 'Primary prevention aims to prevent disease before it occurs. Immunization is a key primary prevention strategy that provides specific protection against diseases.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'In the Philippines, which is the leading cause of morbidity?', 'Cardiovascular disease', 'Acute respiratory infection', 'Tuberculosis', 'Diabetes mellitus', 1, 'Acute respiratory infections consistently rank as the leading cause of morbidity in the Philippines, particularly among children under 5 years old.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'The Expanded Program on Immunization (EPI) was established in the Philippines primarily to:', 'Provide free medicines', 'Reduce morbidity and mortality from vaccine-preventable diseases', 'Train community health workers', 'Build health centers', 1, 'The EPI aims to reduce morbidity, mortality, and disability from diseases preventable by vaccines available under the national immunization program.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'The most effective method of family planning with the highest effectiveness rate is:', 'Oral contraceptive pills', 'Intrauterine device', 'Bilateral tubal ligation', 'Condom use', 2, 'Bilateral tubal ligation (surgical sterilization) has the highest effectiveness rate (>99.5%). It is a permanent method of contraception.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'According to DOH standards, a community health nurse should ideally visit a high-risk pregnant woman:', 'Once during pregnancy', 'Monthly', 'Bi-weekly to weekly', 'Only when complications arise', 2, 'High-risk pregnant women should be monitored more frequently, typically bi-weekly to weekly visits, to identify and manage complications early.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'Which is a characteristic of a therapeutic nurse-patient relationship?', 'The nurse shares personal problems with the patient', 'Professional boundaries are maintained', 'The nurse becomes friends with the patient', 'The relationship continues outside the clinical setting', 1, 'A therapeutic relationship maintains professional boundaries, is patient-centered, goal-directed, and time-limited with clear therapeutic purpose.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'A patient with schizophrenia reports hearing voices telling them to harm themselves. The nurse should FIRST:', 'Ignore the voices as they are not real', 'Assess the patient''s safety and implement precautions', 'Tell the patient to stop listening to the voices', 'Leave the patient alone', 1, 'Command hallucinations directing self-harm are a psychiatric emergency. The nurse must first ensure patient safety by assessing risk and implementing appropriate precautions.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'Which defense mechanism is demonstrated when a patient who is angry at the doctor yells at the nurse?', 'Projection', 'Displacement', 'Denial', 'Regression', 1, 'Displacement involves redirecting emotions from the original source to a substitute target. The patient displaces anger toward the doctor onto the nurse.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'A patient with major depressive disorder is MOST at risk for suicide when:', 'They are most depressed and have no energy', 'During the initial phase of antidepressant therapy', 'When their depression is improving and energy is returning', 'After full recovery', 2, 'Paradoxically, suicide risk is highest when depression begins lifting because the patient now has enough energy to act on suicidal thoughts.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'The nurse is caring for a patient with anorexia nervosa. Which approach is MOST appropriate during mealtimes?', 'Allow the patient to eat alone', 'Sit with the patient during meals', 'Force-feed the patient', 'Ignore eating behaviors', 1, 'Sitting with the patient during meals provides support, prevents food hiding/purging behaviors, and allows monitoring of food intake without being controlling.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'Which neurotransmitter deficiency is associated with depression?', 'Dopamine', 'Serotonin', 'Acetylcholine', 'GABA', 1, 'The monoamine hypothesis of depression links serotonin deficiency to depressive symptoms. Most antidepressants (SSRIs) work by increasing serotonin availability.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'A patient in alcohol withdrawal is at risk for delirium tremens, which typically occurs:', '2-6 hours after last drink', '6-12 hours after last drink', '48-72 hours after last drink', '1 week after last drink', 2, 'Delirium tremens (DTs) typically occurs 48-72 hours after the last drink. It is a medical emergency characterized by confusion, hallucinations, seizures, and autonomic instability.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'The MOST important nursing intervention for a patient experiencing a panic attack is:', 'Administer medication immediately', 'Stay with the patient and speak calmly', 'Encourage the patient to take deep breaths while alone', 'Restrain the patient for safety', 1, 'During a panic attack, the nurse should remain with the patient, speak in a calm and reassuring manner, and guide them through slow, deep breathing exercises.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'Milieu therapy means:', 'Providing a therapeutic environment', 'Prescribing medications', 'Individual psychotherapy', 'Electroconvulsive therapy', 0, 'Milieu therapy uses the total environment (physical setting, social structure, rules) as a therapeutic tool to promote positive behavioral change and social skills.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'A patient with bipolar disorder in a manic episode would MOST likely exhibit:', 'Flat affect and social withdrawal', 'Grandiosity and decreased need for sleep', 'Excessive sleeping and weight gain', 'Obsessive hand washing', 1, 'Manic episodes are characterized by elevated mood, grandiosity, decreased need for sleep, rapid speech, flight of ideas, and risky behavior.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'A patient uses excessive hand washing to cope with anxiety. This is an example of:', 'Phobia', 'Obsessive-compulsive disorder', 'Generalized anxiety disorder', 'Post-traumatic stress disorder', 1, 'Obsessive-compulsive disorder (OCD) involves recurrent, intrusive thoughts (obsessions) and repetitive behaviors (compulsions) such as hand washing to reduce anxiety.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'The DOTS strategy for tuberculosis control stands for:', 'Daily Observed Treatment of Symptoms', 'Directly Observed Treatment Short-course', 'Direct Outpatient Treatment System', 'Dispense Oral Therapy Systematically', 1, 'DOTS (Directly Observed Treatment, Short-course) is the globally recommended TB control strategy where a health worker watches the patient take each dose.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'In epidemiology, the incidence rate refers to:', 'Total number of existing cases', 'Number of new cases in a specific time period', 'Number of deaths per population', 'Recovery rate of a disease', 1, 'Incidence rate measures the number of NEW cases of a disease occurring in a population during a specified time period, reflecting disease occurrence risk.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'What is the primary purpose of a family health assessment?', 'To diagnose diseases', 'To identify health needs and problems of the family', 'To prescribe medications', 'To analyze hospital records', 1, 'Family health assessment identifies the family''s health status, risk factors, resources, and care needs to develop a comprehensive nursing care plan.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'Oral Rehydration Solution (ORS) is the primary treatment for:', 'Pneumonia', 'Dehydration from diarrhea', 'Malnutrition', 'Fever', 1, 'ORS replaces fluids and electrolytes lost through diarrhea. It is the cornerstone of diarrhea management, especially in children, and prevents dehydration-related deaths.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'Which is a key principle of primary health care?', 'Specialization of care', 'Self-reliance and community participation', 'Hospital-centered approach', 'Focus on curative medicine only', 1, 'Primary health care emphasizes self-reliance, community participation, intersectoral collaboration, appropriate technology, and accessible and affordable care for all.', 'Community Health Nursing', 'nursing'),
(v_user_id, 'The nurse observes a patient making a noose from bed sheets. The PRIORITY action is:', 'Document the behavior', 'Take away the sheets and remain with the patient', 'Ask the patient what they are doing', 'Call the family', 1, 'Immediate safety takes priority. The nurse must remove the means of harm (sheets) and stay with the patient while activating the facility''s suicide prevention protocol.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'In crisis intervention, the nurse should prioritize:', 'Long-term psychotherapy', 'Patient safety and immediate coping', 'Medication management', 'Family history assessment', 1, 'Crisis intervention focuses on immediate safety, stabilization, and helping the patient develop coping strategies to manage the current crisis situation.', 'Psychiatric Nursing', 'nursing'),
(v_user_id, 'A patient with antisocial personality disorder is MOST likely to exhibit:', 'Excessive fear of abandonment', 'Disregard for others'' rights and lack of remorse', 'Social withdrawal and flat affect', 'Obsessive attention to detail', 1, 'Antisocial personality disorder is characterized by persistent disregard for the rights of others, deceitfulness, impulsivity, and lack of remorse or empathy.', 'Psychiatric Nursing', 'nursing');

END $$;
