-- ==========================================
-- BLEPP PSYCHOLOGY BOARD EXAM SEED QUESTIONS
-- 120 Questions across key psychology domains
-- ==========================================
-- IMPORTANT: Replace the user_id below with YOUR actual user ID
-- You can find it in Supabase > Authentication > Users
-- ==========================================

DO $$
DECLARE
  v_user_id UUID := '8066d32d-e6ca-4ab5-8a62-c202629d0240'; -- <-- PASTE YOUR USER ID HERE
BEGIN

-- ==========================================
-- INDUSTRIAL/ORGANIZATIONAL PSYCHOLOGY (Items 1-20)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'Which process involves systematically collecting information about the tasks, duties, and responsibilities of a specific job?', 'Job Evaluation', 'Job Analysis', 'Performance Appraisal', 'Job Rotation', 1, 'Job analysis is the fundamental process of identifying exactly what a job entails, serving as the basis for recruitment, selection, and training.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The "KSAOs" in job analysis stand for Knowledge, Skills, Abilities, and:', 'Other characteristics', 'Occupational standards', 'Organization goals', 'Operational tasks', 0, 'KSAOs represent the personal attributes required for a job: Knowledge, Skills, Abilities, and Other characteristics like personality or traits.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which recruitment metric measures the percentage of applicants who move from one stage of the selection process to the next?', 'Cost per hire', 'Yield ratio', 'Selection ratio', 'Time to fill', 1, 'Yield ratios indicate the effectiveness of recruitment sources by showing the proportion of candidates surviving each step of the funnel.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'A "Realistic Job Preview" (RJP) is designed to:', 'Only show the positive aspects of a job', 'Help applicants determine if they fit the job by showing both positives and negatives', 'Increase the number of total applicants', 'Simplify the job description', 1, 'RJPs provide balanced information about a job, reducing early turnover by ensuring applicants have accurate expectations.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which selection method has consistently shown the highest predictive validity for job performance across various jobs?', 'Personality tests', 'Unstructured interviews', 'General mental ability (GMA) tests', 'Reference checks', 2, 'GMA (intelligence) tests are among the strongest predictors of job performance, especially for complex roles.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'In performance appraisal, the "Halo Effect" occurs when:', 'An employee is rated high on all dimensions because of one positive trait', 'An employee is rated based on recent performance only', 'An employee is compared to their peers rather than standards', 'An employee is rated average on everything', 0, 'The halo effect is a cognitive bias where one positive characteristic influences the overall rating of an individual.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The "Six Sigma" methodology primarily focuses on:', 'Increasing employee happiness', 'Reducing defects and variability in processes', 'Expanding into new markets', 'Reducing the workforce', 1, 'Six Sigma is a data-driven approach for eliminating defects and improving quality in organizational processes.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which leadership theory proposes that leaders should adapt their style based on the "readiness" of their followers?', 'Trait Theory', 'Situational Leadership Theory (Hersey-Blanchard)', 'Transformational Leadership', 'Path-Goal Theory', 1, 'Situational Leadership emphasizes adjusting task and relationship behavior based on the maturity or readiness of the subordinate.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'According to Herzberg''s Two-Factor Theory, which of the following is a "Motivator" (not a Hygiene factor)?', 'Salary', 'Working Conditions', 'Recognition', 'Job Security', 2, 'Motivators like recognition and achievement lead to satisfaction, while hygiene factors like salary only prevent dissatisfaction.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Vroom''s Expectancy Theory suggests that motivation is a product of Expectancy, Instrumentality, and:', 'Variable', 'Value', 'Virtue', 'Valence', 3, 'Valence refers to the value or attractiveness an individual places on a particular outcome or reward.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which type of organizational culture emphasizes flexibility, external focus, and "doing things first" (innovation)?', 'Clan Culture', 'Adhocracy Culture', 'Market Culture', 'Hierarchy Culture', 1, 'Adhocracy cultures are characterized by entrepreneurship, creativity, and adaptability.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The "Peter Principle" states that in a hierarchy, every employee tends to:', 'Work harder over time', 'Rise to their level of incompetence', 'Stay at their entry-level position', 'Seek early retirement', 1, 'The Peter Principle suggests that people are promoted based on success in current roles until they reach a role for which they are no longer competent.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which training method involves a trainee observing a master and gradually taking on more responsibility?', 'Case Study', 'Role Playing', 'Apprenticeship', 'Behavioral Modeling', 2, 'Apprenticeship is a classic "learn-by-doing" method under the guidance of an expert.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, '"Glass Ceiling" refers to:', 'Expensive office design', 'Invisible barriers preventing women/minorities from reaching top-level positions', 'Transparent communication from leadership', 'Easily breakable organizational rules', 1, 'The glass ceiling is a metaphor for the artificial barriers that block advancement for certain groups despite their qualifications.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'In I/O Psychology, "Burnout" is most accurately described by: Emotional Exhaustion, Depersonalization, and:', 'Reduced Personal Accomplishment', 'Increased absenteeism', 'Low IQ', 'Hostility', 0, 'Burnout is a syndrome resulting from chronic workplace stress, defined by these three core dimensions.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The "Hawthorne Effect" suggests that employees improve performance when:', 'They receive a raise', 'The lighting is improved', 'They know they are being observed/studied', 'They work in teams', 2, 'The Hawthorne studies revealed that social factors—like being noticed—often influenced productivity more than physical work conditions.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'What is the primary goal of "360-degree feedback"?', 'To give feedback to only the top 10% of performers', 'To gather performance data from supervisors, peers, subordinates, and self', 'To complete performance reviews in 360 minutes', 'To eliminate the need for supervisors', 1, '360-degree feedback provides a comprehensive view of performance by incorporating multiple perspectives.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which type of "Commitment" involves an employee staying with a company because they "want" to (emotional attachment)?', 'Continuance Commitment', 'Normative Commitment', 'Affective Commitment', 'Financial Commitment', 2, 'Affective commitment is the emotional bond an employee feels toward their organization.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, '"Job Enrichment" differs from "Job Enlargement" because it adds:', 'More tasks of the same level', 'Vertically higher-level responsibilities and autonomy', 'More coffee breaks', 'More team members', 1, 'Job enrichment increases the depth of a job (autonomy, responsibility) while enlargement increases the breadth (more tasks).', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The "Big Five" trait most consistently linked to job performance across almost all occupations is:', 'Extraversion', 'Openness', 'Agreeableness', 'Conscientiousness', 3, 'Conscientiousness (being organized, dependable, and disciplined) is the strongest personality predictor of performance.', 'Industrial/Organizational Psychology', 'psychology');

-- ==========================================
-- ABNORMAL PSYCHOLOGY (Items 21-45)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'Which disorder is characterized by the presence of two or more distinct personality states?', 'Schizophrenia', 'Dissociative Identity Disorder', 'Borderline Personality Disorder', 'Bipolar Disorder', 1, 'Dissociative Identity Disorder (formerly Multiple Personality Disorder) involves two or more distinct personality states or identities that recurrently take control of behavior.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'The hallmark feature of Generalized Anxiety Disorder (GAD) is:', 'Panic attacks', 'Excessive worry about various events for at least 6 months', 'Fear of specific objects', 'Recurrent intrusive thoughts', 1, 'GAD is characterized by persistent, excessive, and uncontrollable worry about various everyday matters for at least 6 months, causing significant distress.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Positive symptoms of schizophrenia include:', 'Flat affect', 'Hallucinations and delusions', 'Social withdrawal', 'Poverty of speech', 1, 'Positive symptoms add abnormal experiences and include hallucinations, delusions, disorganized speech, and bizarre behavior. Negative symptoms involve loss of normal functions.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which personality disorder is characterized by a pervasive pattern of instability in interpersonal relationships, self-image, and affects?', 'Narcissistic Personality Disorder', 'Borderline Personality Disorder', 'Antisocial Personality Disorder', 'Schizoid Personality Disorder', 1, 'Borderline Personality Disorder is marked by emotional instability, intense relationships, fear of abandonment, impulsivity, and identity disturbance.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Post-Traumatic Stress Disorder (PTSD) symptoms include all of the following EXCEPT:', 'Flashbacks', 'Hypervigilance', 'Grandiosity', 'Avoidance of trauma-related stimuli', 2, 'PTSD symptoms include re-experiencing (flashbacks, nightmares), avoidance, negative cognitions/mood, and arousal/reactivity. Grandiosity is associated with mania.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Anorexia nervosa is primarily characterized by:', 'Binge eating followed by purging', 'Intense fear of gaining weight and restriction of food intake', 'Eating non-food substances', 'Excessive eating without purging', 1, 'Anorexia nervosa involves restricted food intake, intense fear of weight gain, and distorted body image, often leading to dangerously low body weight.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'The diathesis-stress model suggests that mental disorders result from:', 'Genetics alone', 'Environmental stress alone', 'A combination of biological vulnerability and environmental stressors', 'Poor parenting', 2, 'The diathesis-stress model proposes that mental illness results from a genetic/biological predisposition (diathesis) interacting with environmental stressors.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which disorder is characterized by persistent difficulty discarding possessions regardless of their value?', 'Obsessive-Compulsive Disorder', 'Hoarding Disorder', 'Generalized Anxiety Disorder', 'Specific Phobia', 1, 'Hoarding Disorder involves persistent difficulty discarding possessions due to perceived need to save them, leading to cluttered living spaces and significant distress.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Learned helplessness theory of depression was proposed by:', 'Aaron Beck', 'Martin Seligman', 'Albert Ellis', 'Sigmund Freud', 1, 'Martin Seligman proposed that depression can result from learned helplessness—the belief that one has no control over outcomes, leading to passivity and hopelessness.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which type of delusion involves the belief that one has special powers or is a famous person?', 'Persecutory delusion', 'Grandiose delusion', 'Somatic delusion', 'Erotomanic delusion', 1, 'Grandiose delusions involve inflated beliefs about one''s importance, power, knowledge, or identity, such as believing one is a deity or world leader.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Conversion disorder is classified under which category in the DSM-5?', 'Anxiety disorders', 'Somatic symptom and related disorders', 'Dissociative disorders', 'Personality disorders', 1, 'Conversion disorder (Functional Neurological Symptom Disorder) is classified under somatic symptom disorders, involving neurological symptoms without medical explanation.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'The cognitive triad of depression (Beck''s model) includes negative views of:', 'Past, present, and future', 'Self, world, and future', 'Id, ego, and superego', 'Thoughts, feelings, and behaviors', 1, 'Aaron Beck''s cognitive triad states that depression stems from negative automatic thoughts about oneself, the world, and the future.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which neurotransmitter is MOST implicated in schizophrenia?', 'Serotonin', 'GABA', 'Dopamine', 'Norepinephrine', 2, 'The dopamine hypothesis of schizophrenia proposes that excess dopamine activity in certain brain pathways causes positive symptoms. Antipsychotics block dopamine receptors.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Agoraphobia is best described as:', 'Fear of spiders', 'Fear of heights', 'Fear of open or crowded spaces and situations where escape is difficult', 'Fear of blood', 2, 'Agoraphobia involves fear or anxiety about situations where escape might be difficult, including open spaces, enclosed places, crowds, or being outside the home alone.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which is NOT a cluster B personality disorder?', 'Antisocial', 'Borderline', 'Histrionic', 'Avoidant', 3, 'Cluster B (dramatic/erratic) includes Antisocial, Borderline, Histrionic, and Narcissistic. Avoidant is a Cluster C (anxious/fearful) personality disorder.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Selective mutism is MOST commonly seen in:', 'Adults', 'Children', 'Elderly', 'Adolescents', 1, 'Selective mutism is an anxiety disorder most common in children, characterized by consistent failure to speak in specific social situations despite speaking in others.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which eating disorder involves recurrent episodes of binge eating WITHOUT compensatory behaviors?', 'Anorexia nervosa', 'Bulimia nervosa', 'Binge eating disorder', 'Pica', 2, 'Binge eating disorder involves recurrent binge eating episodes with feelings of loss of control, but unlike bulimia, there are no regular compensatory behaviors (purging, fasting).', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'The primary difference between obsessions and compulsions is that:', 'Obsessions are thoughts; compulsions are behaviors', 'Obsessions are behaviors; compulsions are thoughts', 'They are the same concept', 'Obsessions are voluntary; compulsions are involuntary', 0, 'Obsessions are recurrent, intrusive, unwanted thoughts. Compulsions are repetitive behaviors or mental acts performed to reduce anxiety caused by obsessions.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'La belle indifférence refers to:', 'Extreme emotional distress over symptoms', 'A remarkable lack of concern about one''s symptoms', 'Excessive fear of medical procedures', 'Withdrawal from social situations', 1, 'La belle indifférence describes an inappropriate lack of concern about symptoms, classically associated with conversion disorder.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which disorder involves the repeated pulling out of one''s own hair?', 'Excoriation disorder', 'Trichotillomania', 'Body dysmorphic disorder', 'Somatic symptom disorder', 1, 'Trichotillomania (hair-pulling disorder) involves recurrent pulling out of hair resulting in hair loss, with repeated attempts to decrease or stop the behavior.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Autism Spectrum Disorder is primarily characterized by:', 'Mood instability', 'Deficits in social communication and restricted repetitive behaviors', 'Excessive worry', 'Substance dependence', 1, 'ASD is characterized by persistent deficits in social communication and interaction, along with restricted, repetitive patterns of behavior, interests, or activities.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Which phobia involves the fear of social situations?', 'Claustrophobia', 'Social anxiety disorder', 'Arachnophobia', 'Acrophobia', 1, 'Social anxiety disorder (social phobia) involves marked fear of social situations where one may be scrutinized, judged, or embarrassed.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'Factitious disorder imposed on self (formerly Munchausen syndrome) involves:', 'Genuine physical symptoms with no psychological cause', 'Deliberately fabricating or inducing symptoms for attention', 'Unconscious production of symptoms', 'Malingering for financial gain', 1, 'Factitious disorder involves intentionally producing or feigning physical or psychological symptoms with the primary motivation being to assume the sick role.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'The primary feature of somatic symptom disorder is:', 'Physical symptoms that are intentionally produced', 'Excessive thoughts, feelings, or behaviors related to somatic symptoms', 'Conversion of psychological stress into neurological symptoms', 'Fear of having a serious illness based on misinterpretation of body symptoms', 1, 'Somatic symptom disorder is characterized by one or more somatic symptoms with disproportionate thoughts, feelings, or behaviors related to these symptoms.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'ADHD is classified in the DSM-5 under:', 'Anxiety disorders', 'Neurodevelopmental disorders', 'Disruptive disorders', 'Substance-related disorders', 1, 'ADHD is classified as a neurodevelopmental disorder in the DSM-5, along with intellectual disabilities, ASD, specific learning disorders, and motor disorders.', 'Abnormal Psychology', 'psychology');

-- ==========================================
-- PSYCHOLOGICAL ASSESSMENT (Items 46-65)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'The Rorschach test is an example of a:', 'Self-report inventory', 'Projective personality test', 'Structured interview', 'Neuropsychological test', 1, 'The Rorschach inkblot test is a projective test where responses to ambiguous stimuli are analyzed to assess personality characteristics and emotional functioning.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The MMPI-2 is best described as a:', 'Projective personality test', 'Intelligence test', 'Self-report personality inventory', 'Behavioral observation scale', 2, 'The Minnesota Multiphasic Personality Inventory-2 (MMPI-2) is the most widely used standardized self-report personality questionnaire for assessing psychopathology.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Reliability in psychological testing refers to:', 'Whether the test measures what it claims to measure', 'The consistency and stability of test scores', 'The extent to which test items sample the content domain', 'The degree to which results can be generalized', 1, 'Reliability refers to the consistency and stability of test scores across repeated administrations, forms, raters, or items.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Validity in psychological assessment means:', 'The test produces consistent results', 'The test measures what it is intended to measure', 'The test has standardized scoring', 'The test is free from bias', 1, 'Validity is the degree to which a test actually measures the construct it purports to measure. It is the most fundamental consideration in test evaluation.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The Wechsler Adult Intelligence Scale (WAIS-IV) measures:', 'Personality traits', 'Intelligence and cognitive abilities', 'Academic achievement', 'Vocational interests', 1, 'The WAIS-IV is the most widely used individual intelligence test for adults, measuring verbal comprehension, perceptual reasoning, working memory, and processing speed.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'A standard score with a mean of 100 and a standard deviation of 15 is called an:', 'IQ score', 'T-score', 'Z-score', 'Stanine', 0, 'The IQ score uses a mean of 100 and SD of 15. T-scores have M=50, SD=10. Z-scores have M=0, SD=1. Stanines use a 1-9 scale.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The Thematic Apperception Test (TAT) requires the examinee to:', 'Sort cards into categories', 'Tell stories based on ambiguous pictures', 'Interpret inkblot designs', 'Complete unfinished sentences', 1, 'The TAT is a projective test where subjects create stories about ambiguous scenes depicted in pictures, revealing unconscious motives, concerns, and social perceptions.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Content validity is established by:', 'Correlating test scores with a criterion measure', 'Expert judgment that test items adequately sample the content domain', 'Calculating test-retest correlation', 'Administering the test to a normative sample', 1, 'Content validity is established through systematic examination by subject matter experts who judge whether test items adequately represent the content area being measured.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'A z-score of 0 indicates that the individual''s score is:', 'One standard deviation above the mean', 'At the mean', 'One standard deviation below the mean', 'At the maximum possible score', 1, 'A z-score of 0 indicates the raw score is exactly at the mean of the distribution. Positive z-scores are above the mean; negative are below.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The Beck Depression Inventory is used to assess:', 'Intelligence', 'Anxiety severity', 'Depression severity', 'Personality type', 2, 'The BDI is a 21-item self-report inventory that measures the severity of depressive symptoms. It is one of the most widely used instruments for assessing depression.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Test-retest reliability measures:', 'Whether the test looks like it measures what it should', 'Consistency of scores over time', 'Agreement between different raters', 'Internal consistency of test items', 1, 'Test-retest reliability assesses the stability of test scores over time by administering the same test to the same group on two occasions and correlating the scores.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Which of the following is a structured clinical interview for DSM disorders?', 'Rorschach', 'SCID', 'TAT', 'MMPI', 1, 'The Structured Clinical Interview for DSM (SCID) is a semi-structured interview guide used by clinicians to make reliable DSM diagnoses.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'In a normal distribution, approximately what percentage of scores falls within one standard deviation of the mean?', '50%', '68%', '95%', '99.7%', 1, 'In a normal distribution, approximately 68% of scores fall within ±1 SD, 95% within ±2 SD, and 99.7% within ±3 SD (the 68-95-99.7 rule).', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Cronbach''s alpha is a measure of:', 'Test-retest reliability', 'Inter-rater reliability', 'Internal consistency reliability', 'Content validity', 2, 'Cronbach''s alpha measures internal consistency—the degree to which items in a test are measuring the same construct. Values ≥ 0.70 are generally considered acceptable.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'An IQ score of 70 or below is generally associated with:', 'Gifted intelligence', 'Average intelligence', 'Borderline intellectual functioning', 'Intellectual disability', 3, 'An IQ score of approximately 70 or below (about 2 SD below the mean) along with deficits in adaptive functioning indicates intellectual disability according to DSM-5 criteria.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Construct validity is best described as:', 'How well a test predicts future performance', 'How well test scores reflect the theoretical construct', 'How well test items correspond to a content domain', 'How well two raters agree on scores', 1, 'Construct validity examines whether a test truly measures the theoretical construct it claims to measure, using converging evidence from multiple sources.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The Draw-A-Person (DAP) test is classified as a:', 'Neuropsychological test', 'Achievement test', 'Projective test', 'Self-report inventory', 2, 'The DAP is a projective test in which personality characteristics, self-perception, and emotional functioning are inferred from the features of drawn human figures.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'A percentile rank of 85 means:', '85% of the items were answered correctly', 'The score equals 85 out of 100', 'The individual scored higher than 85% of the comparison group', 'The individual is in the top 85% of performers', 2, 'A percentile rank of 85 means the individual scored higher than 85% of people in the normative sample on that measure.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The Stanford-Binet Intelligence Scale was originally developed by:', 'David Wechsler', 'Alfred Binet and Theodore Simon', 'Raymond Cattell', 'Hans Eysenck', 1, 'Alfred Binet and Theodore Simon developed the first practical intelligence test in 1905 in France. Lewis Terman later adapted it as the Stanford-Binet.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Which scale of the MMPI-2 is designed to detect attempts to "fake good"?', 'F scale', 'L (Lie) scale', 'K scale', 'Hs scale', 1, 'The L (Lie) scale of the MMPI-2 detects attempts to present oneself in an overly favorable or virtuous light. Elevated scores suggest denial of common human flaws.', 'Psychological Assessment', 'psychology');

-- ==========================================
-- DEVELOPMENTAL PSYCHOLOGY (Items 66-85)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'According to Piaget, during which stage does object permanence develop?', 'Sensorimotor', 'Preoperational', 'Concrete operational', 'Formal operational', 0, 'Object permanence—understanding that objects continue to exist even when not visible—develops during the sensorimotor stage (birth to 2 years).', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Piaget''s concrete operational stage is characterized by:', 'Egocentrism', 'Abstract thinking', 'Conservation and logical thinking about concrete events', 'Object permanence', 2, 'The concrete operational stage (7-11 years) involves logical thinking about concrete events, including conservation, classification, and seriation.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Vygotsky''s Zone of Proximal Development (ZPD) refers to:', 'What a child can learn independently', 'The gap between what a child can do alone and with guidance', 'The child''s actual developmental level', 'Genetic potential for learning', 1, 'The ZPD is the range between what a learner can do without help and what they can do with guidance. It highlights the role of social interaction in cognitive development.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'According to Kohlberg, at the conventional level of moral development, moral reasoning is based on:', 'Avoiding punishment', 'Conforming to social norms and maintaining relationships', 'Universal ethical principles', 'Personal pleasure', 1, 'Conventional morality (Stages 3-4) involves conforming to social expectations, maintaining relationships, and following rules to maintain social order.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Harry Harlow''s experiments with monkeys demonstrated the importance of:', 'Cognitive development', 'Contact comfort in attachment formation', 'Language development', 'Moral reasoning', 1, 'Harlow''s studies showed that infant monkeys preferred cloth surrogate mothers over wire mothers with food, demonstrating that contact comfort is crucial for attachment.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'John Bowlby''s attachment theory proposes that:', 'Attachment is purely learned', 'Infants have an innate need to form a close bond with a caregiver', 'Attachment is not important for development', 'Only mothers can form attachments with infants', 1, 'Bowlby proposed that attachment is an innate, evolutionary-based system where infants are biologically predisposed to form close bonds with caregivers for survival.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Mary Ainsworth''s Strange Situation identified which attachment styles?', 'Dependent and independent', 'Secure, avoidant, and anxious-ambivalent', 'Introvert and extrovert', 'Active and passive', 1, 'Ainsworth identified secure, insecure-avoidant, and insecure-ambivalent (resistant) attachment styles. Later, disorganized attachment was added as a fourth category.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Egocentrism in Piaget''s theory is MOST characteristic of which stage?', 'Sensorimotor', 'Preoperational', 'Concrete operational', 'Formal operational', 1, 'Egocentrism—the inability to see things from another''s perspective—is a hallmark of the preoperational stage (2-7 years), demonstrated by the three mountains task.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'The concept of "scaffolding" in Vygotsky''s theory refers to:', 'Building physical structures for children', 'Temporary support provided by a more knowledgeable other', 'Self-directed learning', 'Punishment-based learning', 1, 'Scaffolding involves a more knowledgeable person providing temporary guidance and support to help a learner accomplish tasks within their ZPD, gradually withdrawing help.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Puberty is primarily triggered by hormones from the:', 'Thyroid gland', 'Hypothalamus and pituitary gland', 'Adrenal gland', 'Pancreas', 1, 'The hypothalamus signals the pituitary gland to release gonadotropic hormones (FSH, LH), which stimulate the gonads to produce sex hormones, triggering puberty.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'According to Piaget, formal operational thinking typically emerges around age:', '2 years', '7 years', '11-12 years', '18 years', 2, 'Formal operational thinking (abstract, hypothetical-deductive reasoning) typically begins around age 11-12 and continues to develop through adolescence and adulthood.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Which parenting style is characterized by high warmth and high control?', 'Authoritarian', 'Authoritative', 'Permissive', 'Uninvolved', 1, 'Authoritative parenting combines high warmth/responsiveness with high expectations/control. Research consistently shows it produces the best outcomes for children.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Teratogens are factors that:', 'Promote healthy fetal development', 'Can cause birth defects or abnormalities', 'Only affect the mother', 'Are only genetic in nature', 1, 'Teratogens are environmental agents (drugs, diseases, chemicals, radiation) that can cross the placental barrier and cause harm to the developing embryo or fetus.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Critical periods in development refer to:', 'Times when learning can only happen in school', 'Specific time windows during which certain experiences must occur for normal development', 'Periods of crisis in adolescence', 'The time between developmental milestones', 1, 'Critical periods are specific time windows when the organism is particularly sensitive to certain environmental stimuli. If the stimulus is absent, development may be permanently impaired.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'The rooting reflex in newborns involves:', 'Grasping when something touches the palm', 'Turning the head toward a stroke on the cheek', 'Spreading the toes when the sole is stroked', 'Startling in response to loud noises', 1, 'The rooting reflex causes newborns to turn their head toward a stimulus that touches their cheek, facilitating breastfeeding. It typically disappears by 3-4 months.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Stranger anxiety typically appears at what age?', '1-2 months', '6-8 months', '12-15 months', '2-3 years', 1, 'Stranger anxiety typically emerges around 6-8 months as infants develop the ability to distinguish familiar from unfamiliar people, coinciding with attachment formation.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'According to Erikson, the developmental task of old age (65+) is:', 'Identity vs. Role Confusion', 'Generativity vs. Stagnation', 'Integrity vs. Despair', 'Intimacy vs. Isolation', 2, 'Integrity vs. Despair (65+) involves reflecting on life. Successful resolution brings wisdom and acceptance; failure leads to regret and despair over unfulfilled goals.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Lawrence Kohlberg''s highest level of moral reasoning is:', 'Preconventional', 'Conventional', 'Postconventional', 'Universal', 2, 'Postconventional morality (Stages 5-6) involves reasoning based on abstract principles of justice, rights, and ethics that may transcend laws and social conventions.', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Jean Piaget believed that cognitive development occurs through:', 'Reward and punishment', 'Assimilation and accommodation', 'Classical conditioning', 'Social learning', 1, 'Piaget proposed that children construct knowledge through assimilation (fitting new info into existing schemas) and accommodation (modifying schemas to incorporate new info).', 'Developmental Psychology', 'psychology'),
(v_user_id, 'Theory of Mind typically develops around age:', '1 year', '2 years', '4-5 years', '7-8 years', 2, 'Theory of Mind—the ability to understand that others have beliefs, desires, and perspectives different from one''s own—typically develops around age 4-5, as demonstrated by false belief tasks.', 'Developmental Psychology', 'psychology');

-- ==========================================
-- SOCIAL, I/O & RESEARCH PSYCHOLOGY (Items 86-120)
-- ==========================================

INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'Solomon Asch''s conformity experiments demonstrated that individuals will:', 'Always make independent judgments', 'Conform to group pressure even when the group is clearly wrong', 'Only conform in ambiguous situations', 'Never change their opinions', 1, 'Asch''s line experiments showed that about 75% of participants conformed at least once to an obviously incorrect group answer, demonstrating the power of social pressure.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Stanley Milgram''s obedience study examined:', 'The effects of conformity on perception', 'Obedience to authority figures', 'Bystander intervention', 'Group polarization', 1, 'Milgram''s studies showed that ordinary people would administer what they believed were dangerous electric shocks when ordered by an authority figure.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The bystander effect refers to:', 'People helping more when others are present', 'Decreased likelihood of helping when more bystanders are present', 'Increased aggression in crowds', 'Conformity in social situations', 1, 'The bystander effect describes the phenomenon where individuals are less likely to offer help when others are present, due to diffusion of responsibility.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Cognitive dissonance theory was proposed by:', 'Solomon Asch', 'Leon Festinger', 'Philip Zimbardo', 'Albert Bandura', 1, 'Leon Festinger''s cognitive dissonance theory states that people experience discomfort when holding conflicting cognitions and are motivated to reduce this inconsistency.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The fundamental attribution error is the tendency to:', 'Overestimate situational factors in explaining others'' behavior', 'Overestimate dispositional factors when explaining others'' behavior', 'Underestimate one''s own abilities', 'Attribute success to luck', 1, 'The fundamental attribution error involves attributing others'' behaviors primarily to internal (dispositional) characteristics while underestimating situational influences.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'In-group bias refers to:', 'Preferring members of one''s own group', 'Treating all groups equally', 'Avoiding groups altogether', 'Conforming to outgroup norms', 0, 'In-group bias is the tendency to favor one''s own group (in-group) over other groups (out-groups) in evaluations, attributions, and resource allocation.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Philip Zimbardo''s Stanford Prison Experiment demonstrated:', 'The stability of personality traits', 'The power of social roles and situations on behavior', 'The effectiveness of punishment', 'Individual differences in intelligence', 1, 'The Stanford Prison Experiment showed how quickly people conform to social roles (guard vs. prisoner), demonstrating the powerful influence of situations over individual dispositions.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The halo effect in perception refers to:', 'Judging a person negatively based on one trait', 'Allowing one positive trait to influence overall judgment', 'Ignoring negative information about a person', 'Rating everyone as average', 1, 'The halo effect occurs when a positive impression of one characteristic (e.g., attractiveness) leads to favorable judgments about unrelated characteristics (e.g., intelligence).', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Groupthink occurs when:', 'Group members think independently', 'Desire for group harmony overrides realistic evaluation of alternatives', 'Groups always make better decisions than individuals', 'Groups are composed of diverse members', 1, 'Groupthink (Janis) occurs when group cohesion and desire for unanimity suppress critical evaluation, leading to poor decision-making.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The mere exposure effect suggests that:', 'Familiarity breeds contempt', 'Repeated exposure to a stimulus increases liking for it', 'People prefer novel stimuli', 'Exposure has no effect on attitudes', 1, 'The mere exposure effect (Zajonc) demonstrates that repeated exposure to a stimulus, even without conscious recognition, increases positive feelings toward it.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'In I/O psychology, job satisfaction is MOST strongly predicted by:', 'Salary alone', 'The fit between the person and the job/organization', 'Office location', 'Number of vacation days', 1, 'Person-job fit and person-organization fit are the strongest predictors of job satisfaction, encompassing alignment of values, skills, and expectations.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Herzberg''s Two-Factor Theory distinguishes between:', 'Intrinsic and extrinsic rewards', 'Hygiene factors and motivators', 'Needs and wants', 'Inputs and outputs', 1, 'Herzberg distinguished between hygiene factors (salary, conditions—prevent dissatisfaction) and motivators (achievement, recognition—promote satisfaction).', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Transformational leadership is characterized by:', 'Focus on rewards and punishments', 'Inspiring followers and promoting change through vision', 'Maintaining the status quo', 'Micromanaging employees', 1, 'Transformational leaders inspire, motivate, and intellectually stimulate followers, creating a vision for change and empowering others to achieve extraordinary outcomes.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'The Hawthorne Effect refers to:', 'Improved performance because participants know they are being observed', 'Decreased motivation in the workplace', 'The effect of noise on productivity', 'Burnout from overwork', 0, 'The Hawthorne Effect describes the phenomenon where people modify their behavior simply because they know they are being studied or observed.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'An independent variable in an experiment is:', 'The variable that is measured', 'The variable that is manipulated by the researcher', 'A confounding factor', 'The outcome variable', 1, 'The independent variable (IV) is the factor deliberately manipulated by the researcher to observe its effect on the dependent variable (DV).', 'Psychological Assessment', 'psychology'),
(v_user_id, 'A double-blind study is designed to minimize:', 'Sample size issues', 'Experimenter and participant bias', 'Ethical concerns', 'External validity problems', 1, 'In double-blind studies, neither participants nor researchers know who is in the experimental or control group, minimizing both experimenter and participant bias.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'A correlation coefficient of -0.85 indicates:', 'A weak positive relationship', 'A strong negative relationship', 'No relationship', 'A perfect positive relationship', 1, 'A correlation of -0.85 indicates a strong negative (inverse) relationship: as one variable increases, the other tends to decrease. The strength is indicated by the absolute value.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Random assignment in an experiment serves to:', 'Make the sample represent the population', 'Equalize group differences and control for confounding variables', 'Increase sample size', 'Ensure informed consent', 1, 'Random assignment distributes participant characteristics evenly across groups, controlling for confounding variables and making groups equivalent before treatment.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'A Type I error in statistical testing occurs when:', 'A true null hypothesis is rejected', 'A false null hypothesis is not rejected', 'The sample size is too large', 'The data is not normally distributed', 0, 'A Type I error (alpha error, false positive) occurs when the null hypothesis is true but is incorrectly rejected, concluding a significant effect when there is none.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The mean, median, and mode are all measures of:', 'Variability', 'Central tendency', 'Correlation', 'Statistical significance', 1, 'Measures of central tendency describe the center of a data distribution. The mean is the arithmetic average, the median is the middle value, and the mode is the most frequent.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'External validity refers to:', 'Whether the study measures what it claims to measure', 'The degree to which results can be generalized to other settings', 'Internal consistency of a measure', 'The accuracy of the statistical analysis', 1, 'External validity is the extent to which findings from a study can be generalized to other populations, settings, and time periods beyond the specific study context.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Informed consent in research requires:', 'Participants receiving payment', 'Participants understanding the study and voluntarily agreeing to participate', 'Participants committing to complete the study', 'Participants being deceived about the study''s purpose', 1, 'Informed consent requires that participants are told about the study''s purpose, procedures, risks, and benefits, and voluntarily agree to participate without coercion.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The ethical principle of beneficence in psychology means:', 'Do no harm', 'Act in the best interest of the client', 'Maintain confidentiality', 'Respect autonomy', 1, 'Beneficence requires psychologists to actively contribute to the well-being of those they work with, going beyond merely avoiding harm (non-maleficence).', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Confidentiality can be legally broken when:', 'The client is annoying', 'There is imminent danger to self or others', 'The therapist disagrees with the client', 'The client misses appointments', 1, 'Confidentiality can be breached when there is a duty to warn—imminent danger to self or others (Tarasoff ruling), child/elder abuse, or court order.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The Philippine Mental Health Act (RA 11036) aims to:', 'Build more psychiatric hospitals', 'Establish a national mental health policy and ensure mental health rights', 'Restrict access to mental health services', 'Mandate medication for all mental health patients', 1, 'RA 11036 establishes a national mental health policy, protects the rights of persons with mental health conditions, and integrates mental health into the public health system.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Which organization governs the professional practice of psychology in the Philippines?', 'Philippine Medical Association', 'Psychological Association of the Philippines', 'Professional Regulation Commission', 'Department of Health', 2, 'The Professional Regulation Commission (PRC) through the Board of Psychology regulates the licensure and professional practice of psychologists in the Philippines.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'The RA 10029 (Philippine Psychology Act) requires psychologists to:', 'Work only in hospitals', 'Obtain a license before practicing psychology', 'Practice without supervision', 'Focus only on research', 1, 'RA 10029 requires individuals to pass the licensure exam and obtain a license from the PRC before practicing psychology or psychometrics in the Philippines.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Dual relationships in therapy should be avoided primarily because they:', 'Make therapy more expensive', 'Can impair professional judgment and exploit the client', 'Are always illegal', 'Make scheduling difficult', 1, 'Dual relationships (having both a professional and personal relationship) can compromise objectivity, create conflicts of interest, and potentially exploit the power differential.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Deception in psychological research is:', 'Never acceptable', 'Acceptable only when scientifically justified and participants are debriefed', 'Always acceptable', 'Only acceptable with children', 1, 'Deception may be used when necessary for scientific validity, no alternatives exist, the study poses minimal risk, and participants receive a thorough debriefing afterwards.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Self-serving bias is the tendency to:', 'Attribute success to internal factors and failure to external factors', 'Take responsibility for all outcomes', 'Attribute success to luck', 'Blame oneself for everything', 0, 'Self-serving bias leads people to attribute their successes to personal factors (ability, effort) and failures to external factors (luck, difficulty), protecting self-esteem.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Which type of research design follows the same group of people over time?', 'Cross-sectional', 'Longitudinal', 'Case study', 'Cross-sequential', 1, 'Longitudinal designs study the same participants over an extended period, allowing researchers to observe changes and development within individuals over time.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Albert Ellis developed which therapeutic approach?', 'Psychoanalysis', 'Gestalt therapy', 'Rational Emotive Behavior Therapy (REBT)', 'Logotherapy', 2, 'Ellis developed REBT, which focuses on identifying and challenging irrational beliefs (e.g., "I must be perfect") that lead to emotional disturbance and replacing them with rational ones.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Systematic desensitization is based on the principle of:', 'Operant conditioning', 'Classical conditioning (counterconditioning)', 'Observational learning', 'Cognitive restructuring', 1, 'Systematic desensitization (Wolpe) uses classical conditioning principles to pair relaxation with anxiety-producing stimuli in a gradual hierarchy, replacing fear with relaxation.', 'Abnormal Psychology', 'psychology'),
(v_user_id, 'The Yerkes-Dodson Law states that:', 'More stress always leads to better performance', 'Moderate arousal leads to optimal performance', 'Low arousal is always best for performance', 'Arousal has no effect on performance', 1, 'The Yerkes-Dodson Law describes an inverted-U relationship between arousal and performance: moderate arousal leads to optimal performance, while too little or too much impairs it.', 'Psychological Assessment', 'psychology'),
(v_user_id, 'Which approach to psychology emphasizes free will, personal growth, and self-actualization?', 'Behaviorism', 'Psychoanalysis', 'Humanism', 'Structuralism', 2, 'Humanistic psychology (Maslow, Rogers) emphasizes free will, personal growth, self-actualization, and the inherent goodness of people. It is the "third force" in psychology.', 'Industrial/Organizational Psychology', 'psychology'),
(v_user_id, 'Burnout in the workplace is characterized by:', 'Increased motivation', 'Emotional exhaustion, depersonalization, and reduced accomplishment', 'Higher job satisfaction', 'Increased productivity', 1, 'Burnout (Maslach) involves three dimensions: emotional exhaustion, depersonalization (cynicism toward clients/work), and reduced personal accomplishment.', 'Industrial/Organizational Psychology', 'psychology');


INSERT INTO public.questions (user_id, question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, module) VALUES
(v_user_id, 'In an experiment, the variable that is deliberately manipulated by the researcher is called the:', 'Dependent variable', 'Confounding variable', 'Independent variable', 'Control variable', 2, 'The independent variable (IV) is the presumed cause that the experimenter manipulates, while the dependent variable (DV) is the measured outcome.', 'Research Methods', 'psychology'),
(v_user_id, 'Which of the following correlation coefficients indicates the strongest relationship between two variables?', '+0.65', '-0.88', '+0.10', '-0.50', 1, 'The strength of a correlation is determined by its absolute value (how close it is to 1.0 or -1.0). Therefore, -0.88 is stronger than +0.65.', 'Research Methods', 'psychology'),
(v_user_id, 'A test that yields consistent results every time it is administered is said to have high:', 'Validity', 'Reliability', 'Standardization', 'Significance', 1, 'Reliability refers to the consistency or repeatability of a measure. A test can be reliable without being valid, but it cannot be valid unless it is reliable.', 'Research Methods', 'psychology'),
(v_user_id, 'If a researcher wants to ensure that their new intelligence test actually measures intelligence and not just reading comprehension, they are concerned with:', 'Construct validity', 'Test-retest reliability', 'Inter-rater reliability', 'External validity', 0, 'Construct validity is the degree to which a test accurately measures the theoretical concept or construct it was designed to measure.', 'Research Methods', 'psychology'),
(v_user_id, 'In a double-blind experimental design:', 'Only the participants are unaware of the hypothesis.', 'Only the researchers are unaware of group assignments.', 'Neither the participants nor the researchers interacting with them know who is in the experimental or control group.', 'The independent variable is hidden from the ethics committee.', 2, 'Double-blind studies prevent both participant expectations (placebo effect) and experimenter bias from influencing the results.', 'Research Methods', 'psychology'),
(v_user_id, 'A Type I error in hypothesis testing occurs when a researcher:', 'Fails to reject a false null hypothesis.', 'Rejects a true null hypothesis.', 'Calculates the standard deviation incorrectly.', 'Uses a biased sample.', 1, 'A Type I error (false positive) happens when a researcher claims there is a significant effect or difference when, in reality, there is none.', 'Research Methods', 'psychology'),
(v_user_id, 'Which measure of central tendency is most affected by extreme outlier scores in a dataset?', 'Mean', 'Median', 'Mode', 'Range', 0, 'The mean (average) is highly sensitive to extreme scores (outliers), which can skew the data. The median is a better measure of central tendency for skewed distributions.', 'Research Methods', 'psychology'),
(v_user_id, 'In a normal distribution, approximately what percentage of scores fall within one standard deviation above and below the mean?', '34%', '68%', '95%', '99.7%', 1, 'According to the empirical rule (68-95-99.7 rule) for normal distributions, roughly 68% of data falls within one standard deviation of the mean.', 'Research Methods', 'psychology'),
(v_user_id, 'Providing a clear, precise, and measurable definition of how a variable will be manipulated or measured is known as creating a(n):', 'Hypothesis', 'Theory', 'Operational definition', 'Random assignment', 2, 'Operational definitions translate abstract concepts (e.g., "aggression") into concrete, measurable procedures (e.g., "number of times a child hits a toy"), allowing for replication.', 'Research Methods', 'psychology'),
(v_user_id, 'A researcher studies a cohort of 10-year-olds and checks back in with the exact same group when they are 20, 30, and 40 years old. This is an example of a:', 'Cross-sectional design', 'Longitudinal design', 'Cross-sequential design', 'Case study', 1, 'Longitudinal research studies the same group of individuals over an extended period to observe developmental changes over time.', 'Research Methods', 'psychology'),
(v_user_id, 'To minimize pre-existing differences between the control and experimental groups, researchers should use:', 'Random sampling', 'Random assignment', 'Convenience sampling', 'Stratified sampling', 1, 'Random assignment ensures every participant has an equal chance of being placed in any group, effectively neutralizing individual differences between the groups.', 'Research Methods', 'psychology'),
(v_user_id, 'A detailed, in-depth investigation of a single individual or a small group, often used in clinical psychology, is called a:', 'Survey', 'Naturalistic observation', 'Experiment', 'Case study', 3, 'Case studies provide rich, detailed qualitative data about rare or specific phenomena, though their findings are difficult to generalize to the broader population.', 'Research Methods', 'psychology'),
(v_user_id, 'An extraneous variable that systematically varies with the independent variable and could explain the results is a:', 'Dependent variable', 'Confounding variable', 'Placebo variable', 'Continuous variable', 1, 'A confounding variable is an outside factor that affects the variables being studied, making it unclear whether the IV or the confound caused the change in the DV.', 'Research Methods', 'psychology'),
(v_user_id, 'In inferential statistics, a p-value of less than 0.05 (p < .05) generally indicates that:', 'The results are due to chance.', 'The hypothesis is completely proven.', 'The results are statistically significant.', 'The sample size was too small.', 2, 'A p-value < .05 means there is less than a 5% probability that the observed results occurred by chance, leading researchers to reject the null hypothesis.', 'Research Methods', 'psychology'),
(v_user_id, 'Which ethical principle requires psychologists to explain the true purpose of a study to participants after the data has been collected?', 'Informed consent', 'Confidentiality', 'Debriefing', 'Right to withdraw', 2, 'Debriefing occurs at the end of a study. Researchers must explain the true nature, results, and conclusions of the research, and clarify any deception used.', 'Research Methods', 'psychology'),
(v_user_id, 'Watching primates interact in the wild without intervening or attempting to control the environment is an example of:', 'Experimental research', 'Naturalistic observation', 'Correlational research', 'Archival research', 1, 'Naturalistic observation involves observing subjects in their natural environment without any manipulation, which increases ecological validity.', 'Research Methods', 'psychology'),
(v_user_id, 'The tendency for participants to answer questions in a way that they think will be viewed favorably by others is known as:', 'Experimenter bias', 'Social desirability bias', 'Confirmation bias', 'Hindsight bias', 1, 'Social desirability bias is a common issue in self-report surveys where participants underreport undesirable behaviors and overreport positive ones.', 'Research Methods', 'psychology'),
(v_user_id, 'If a study finds that higher rates of ice cream consumption are associated with higher rates of shark attacks, the researcher must remember that:', 'Ice cream causes shark attacks.', 'Shark attacks cause people to eat ice cream.', 'Correlation does not imply causation.', 'The data is invalid.', 2, 'Correlation only measures the relationship between two variables. In this case, a third variable (like warm summer weather) likely causes both.', 'Research Methods', 'psychology'),
(v_user_id, 'A sampling technique where the population is divided into subgroups (strata) and random samples are taken from each subgroup to ensure representation is called:', 'Simple random sampling', 'Snowball sampling', 'Stratified random sampling', 'Cluster sampling', 2, 'Stratified random sampling ensures that specific demographic characteristics (like age or gender) are proportionately represented in the final sample.', 'Research Methods', 'psychology'),
(v_user_id, 'The group in an experiment that receives the placebo or no treatment at all serves as the baseline for comparison. This is the:', 'Experimental group', 'Control group', 'Sample group', 'Population group', 1, 'The control group does not receive the active manipulation (IV), providing a baseline to compare against the experimental group to see if the treatment had an effect.', 'Research Methods', 'psychology'); 

END $$;
